### ISSUE TITLE
traverse does not preserve the extended type

### ISSUE THREAD

**Issue by sha49** [philpl/extendable-immutable#16]
When I use `traverse` (http://ramdajs.com/docs/#traverse) over a data structure that it is an extended Map, List etc... the result data structure goes back to a plain immutablejs Map, List etc... not a extended Map, List anymore.

Not sure if this should be done on this package or not.

**Comment by sha49** [comment]
We solved the problem by defining the proper empty method on our extended types:

```
  get empty () {
    return new this.constructor({})
  }
```

**Comment by kitten** [comment]
Hiya, I'm not really sure how ramda's traverse is implemented, but this should theoretically not be necessary, since al methods are wrapped: https://github.com/philpl/extendable-immutable/blob/master/src/util/createExtendable.js#L65

Or is it expecting a `.empty` getter property that Immutable implements without my knowledge?
