### ISSUE TITLE
Using Immutable-js Map given functions

### ISSUE THREAD

**Issue by CarolineBoyer** [philpl/extendable-immutable#17]
Hello !

I was searching for a way to implement my own toString() function on the immutable-js lib when I came around yours ! So thank you very much for this work, I was happy to find it :)

Now I did came here for an issue... I tried extending my class :
```js
import { List, Record } from 'immutable';
import { Map } from 'extendable-immutable';

export default class ParseTree extends Map {
    constructor ( token = "empty", data = {}, children = List() ) {
        super( { token:token, data: ParseTree.initData(token, data), children:children });
    }
```

**Question 1**- Can you do a mix of your library and immutable's ? As ParseTree is a Map from you, but it's children is directly from Immutable List. It shouldn't change much to me... But considering the behavior I have after that, I prefer to check. 

I then test a few things : 
```js
    toString ( ) {
        console.log(this.get("token")); //undefined
    }
```

Now I probably did something wrong because ... Well it did work when using a Map from immutable. 

**Question 2** - Is it related to #7 ? Did I fail to build my constructor ? :( 
Do you think you could explain it to me so I can help you do some docs ?

Many thanks again for letting us deal with those overriding issues :D

**Comment by kitten** [comment]
Gosh, I haven’t worked on this for a while 😅 I’ll take a look when I’m back from my holidays on Monday. This was honestly just a really simple project which I never ended up using in prod so that’s why no docs exist

**Comment by CarolineBoyer** [comment]
Thank you for that ! Can't wait to hear from you !

**Comment by kitten** [comment]
Sorry for the delay! Totally forgot about this issue

> Can you do a mix of your library and immutable's ? As ParseTree is a Map from you, but it's children is directly from Immutable List. It shouldn't change much to me..

Yes, you can mix and match them as you'd like. They're just instances after all :wink:

> Now I probably did something wrong because ... Well it did work when using a Map from immutable.

You can't do the same with Immutable since extensions won't work anyway. The constructor must accept other data than just your own. I suggest you create a static method for creation here.

This works just fine: https://codesandbox.io/s/n05pjv292m

Also note how you can still change the constructor to accept another parameter.

You could also theoretically detect whether the input is of Immutable base type and then call the constructor with it without some special logic. That would allow the Immutable reification to pass through cleanly.

i.e.:

```js
import { Map as ImmutableMap } from 'immutable'
import { Map } from 'extendable-immutable'

class Collection extends Map {
  constructor(data) {
    if (data instanceof ImmutableMap) {
      return super(data); // note that returning here is very important
    }

    return super().set("data", data); // namespacing example
  }
}
```

I haven't tested the above, but something like it should theoretically work 🤔
