### ISSUE TITLE
Processing data in constructor

### ISSUE THREAD

**Issue by NSLS** [philpl/extendable-immutable#7]
Hi! I have been trying to implement this library in my project and faced an issue with processing data in the constructor.

Essentially, the idea was to create an OrderedMap with id => Map mapping from a raw JS array.

The code for this initialization looks like this
```
import {OrderedMap} from 'extendable-immutable';

export class Collection extends OrderedMap {
	constructor(raw) {
	    const items = raw.reduce(
	        (reduction, item) => reduction.set(item.id, Immutable.fromJS(item)),
	        Immutable.OrderedMap()
	    );

	    super(items);
	}
}

...

const items = new Collection([{id: 1}, {id: 2}]);
```

At first everything looked fine, until I've tried to use `.filter()` on such Collection, and for some reason it doesn't work as expected. Instead I get only one Map, however, if any conversion method is called before `.filter()`, such as `.toList()` or `.toMap()`, filter works as expected.

Could you help me out to figure out the problem?

Best regards,
Thanks.

**Comment by philpl** [comment]
Hm, this is a tricky one to imagine.

To break down what is happening, your `super` call should receive your OrderedMap and pass it on to `this.__wrapImmutable(new Base(val))`. `__wrapImmutable` should then basically instantiate a `Collection` and copy all values over. Then the result is being returned. Since you never return the result of `super()`, this is going to end up being an empty Collection with an incorrect reference.

You could either just return the result of `super` with `return super(items)`, or actually perform the operations on the empty `Collection` that `super` returns, like so: http://www.webpackbin.com/E1zf7F74G

**Comment by NSLS** [comment]
I have completely missed the ability to return the value from super().

Very grateful for your clarification.

**Comment by philpl** [comment]
@NSLS No worries! Would you think it's a good idea to add this to the readme? Actually, I haven't written docs yet, since there's not a lot of people using this yet.

**Comment by NSLS** [comment]
@philpl It might be useful, so why not.

**Comment by NSLS** [comment]
Hello again. I have only got a chance to implement your suggestion now, and after testing your bin, I have faced the same issue as I was facing before, you can have a look at it here:
http://www.webpackbin.com/4yjfvgtSM

If you don't have the time to fix this, you could just point out, what is the issue and I could try to make a PR myself.

Thanks!

**Comment by philpl** [comment]
@NSLS You need to prepare the constructor for receiving other values than just your own input. Immutable has a `reify` function that converts some internal `Seq`s back to for example an OrderedMap, by passing it to the constructor.

http://www.webpackbin.com/EklkQ1TSM
